pipeline:
  docker:
    image: plugins/docker
    repo: registry.tstllc.net/llisk/alpine-nginx
    force_tag: true

publish:
  docker:

    tag:
      - latest
    when:
      branch:
        include: [ master, release/* ]

publish:
  docker:
    repo: registry.tstllc.net/llisk/alpine-nginx
    tag:
      - ${DRONE_BRANCH}-latest
      - ${DRONE_BRANCH}.build-${DRONE_BUILD_NUMBER}
    when:
      branch:
        exclude: [ master ]

publish:
  ecr:
    image: plugins/ecr
    access_key: ${AWS_ACCESS_KEY_ID}
    secret_key: ${AWS_SECRET_ACCESS_KEY}
    repo: 945362765384.dkr.ecr.us-east-1.amazonaws.com/util/${DRONE_REPO_NAME}
    region: us-east-1
    tags:
      - latest
      - ${DRONE_BRANCH}.build-${DRONE_COMMIT_SHA:0:8}
