pipeline:
  docker:
    image: plugins/docker
    repo: registry.tstllc.net/llisk/alpine-nginx
    username: ${REPO_USERNAME}
    password: ${REPO_PASSWORD}
    email: ${REPO_EMAILADDR}
    registry: registry.tstllc.net
    force_tag: true
  docker:
    tag:
      - latest
    when:
      branch:
        include: [ master, release/* ]
  docker:
    repo: registry.tstllc.net/llisk/alpine-nginx
    tag:
      - ${DRONE_BRANCH}-latest
      - ${DRONE_BRANCH}.build-${DRONE_BUILD_NUMBER}
    when:
      branch:
        exclude: [ master ]
